version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            mkdir ~/.triplequote
            printf "floating-key=%s\n" "$HYDRA_SERVER_KEY" > ~/.triplequote/hydra.license
      - run:
          name: Build
          command: |
            sbt Test/compile
      - persist_to_workspace:
          root: "/tmp/workspace"
          paths:
            - "*"

  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /tmp/workspace
    parallelism: 3
    steps:
      - attach_workspace:
          at: "/tmp/workspace/"
      - run:
          name: Run tests
          command: sbt test

workflows:
  version: 2.1
  cicd:
    jobs:
      - build:
          context: org-global-cph
      - test:
          context: org-global-cph
          requires:
            - build
