version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-cache-{{ .Branch }}-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/Dependencies.scala" }}
      - run:
          name: Set up Sbt
          command: |
            echo "credentials += Credentials(\"Artifactory Realm\", \"liveintent.jfrog.io\", \"${ARTIFACTORY_USERNAME}\", \"${ARTIFACTORY_PASSWORD}\")" >~/.sbt/1.0/sonatype.sbt
      - run:
          name: Setup Hydra
          command: |
            mkdir ~/.triplequote
            printf "floating-key=%s\n" "$HYDRA_SERVER_KEY" > ~/.triplequote/hydra.license
      - run:
          name: Build
          command: |
            sbt Test/compile
      - save_cache:
          key: v1-deps-cache-{{ .Branch }}-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/Dependencies.scala" }}
          paths:
            - ~/.cache/coursier
            - ~/.sbt
      - persist_to_workspace:
          root: "/tmp/workspace"
          paths:
            - "*"

  test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /tmp/workspace
    parallelism: 3
    steps:
      - attach_workspace:
          at: "/tmp/workspace/"
      - restore_cache:
          keys:
            - v1-deps-cache-{{ .Branch }}-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/Dependencies.scala" }}
      - run:
          name: Set up Sbt
          command: |
            echo "credentials += Credentials(\"Artifactory Realm\", \"liveintent.jfrog.io\", \"${ARTIFACTORY_USERNAME}\", \"${ARTIFACTORY_PASSWORD}\")" >~/.sbt/1.0/sonatype.sbt
      - run:
          name: Setup
          command: |
            mkdir ~/.triplequote
            printf "floating-key=%s\n" "$HYDRA_SERVER_KEY" > ~/.triplequote/hydra.license
      - run:
          name: Set up Hydra
          command: |
            mkdir ~/.triplequote
            printf "floating-key=%s\n" "$HYDRA_SERVER_KEY" > ~/.triplequote/hydra.license
      - run:
          name: Test
          command: sbt test

workflows:
  version: 2.1
  cicd:
    jobs:
      - build:
          context: org-global-cph
      - test:
          context: org-global-cph
          requires:
            - build
